os: linux
language: python
install: source .travis/install.sh
before_script: source .travis/env.sh
script: make install test
after_success: bash <(curl -s https://codecov.io/bash) -f "!*#tests#*"
jobs:
  include:
    - name: Style
      python: 3.7
      install:
        - pip install black flake8 flake8-bugbear flake8-comprehensions flake8-quotes pep8-naming isort pydocstyle
      before_script: skip
      script:
        - flake8
        - black . --check
        - isort . --check
        - pydocstyle src
    - python: 3.6
      addons: &apt
        apt:
          packages:
            - gfortran
            - libblas-dev
            - liblapack-dev
            - mpi-default-dev
            - mpi-default-bin
            - libscalapack-mpi-dev
    - python: 3.6
      env: CMAKE_FLAGS="-DENABLE_SCALAPACK_MPI=ON" MPI_NODES=1
      addons: *apt
    - python: 3.7
      env: CMAKE_FLAGS="-DENABLE_SCALAPACK_MPI=ON" MPI_NODES=2
      addons: *apt
    - language: minimal
      os: osx
      osx_image: xcode11
      env: CMAKE_FLAGS="-DENABLE_SCALAPACK_MPI=ON" MPI_NODES=2
      addons: &brew
        homebrew:
          packages:
            - open-mpi
            - scalapack
    - name: Documentation
      python: 3.7
      install: skip
      before_script: skip
      script: make doc
      workspaces:
        create:
          name: ws1
          paths:
            - docs/build
      addons:
        apt:
          packages:
            - gfortran
    - stage: deploy
      name: Documentation
      language: minimal
      install: skip
      script: skip
      if: branch = master
      workspaces:
        use: ws1
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: docs/build
