[build-system]
requires = ["poetry_core>=1", "cffi", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pymbd"
version = "0.10.3"
description = "Many-body dispersion library"
authors = ["Jan Hermann <dev@jan.hermann.name>"]
readme = "README.md"
packages = [{ include = "pymbd", from = "src" }]
repository = "https://github.com/jhrmnn/libmbd"
documentation = "https://jhrmnn.github.io/libmbd/pymbd"
license = "MPL-2.0"
build = "build.py"
include = ["src/mbd.h"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Fortran",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[tool.poetry.dependencies]
python = "^3.6"
scipy = "^1"
numpy = "^1"
cffi = "^1"
pytest = { version = "^5", optional = true }
mpi4py = { version = "^3", optional = true }

[tool.poetry.extras]
mpi = ["mpi4py"]
test = ["pytest"]

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
flake8-bugbear = "^19"
flake8-comprehensions = "^2"
flake8-quotes = "^2"
black = ">=20-beta.0"
pydocstyle = "^5"
pep8-naming = "^0.8"
isort = "^5"

[tool.black]
target-version = ["py36"]
skip-string-normalization = true
